[package]
name = "solsynth-mail"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
solsynth-db = { path = "../solsynth-db" }
solsynth-utils = { path = "../solsynth-utils" }

anyhow.workspace = true
async-trait.workspace = true
tokio.workspace = true
axum.workspace = true
axum-extra = { workspace = true, features = ["cookie"] }
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
tracing.workspace = true
thiserror.workspace = true
regex.workspace = true
url.workspace = true

# Email
lettre = { version = "0.11", features = ["tokio1-native-tls", "builder", "smtp-transport"] }
handlebars = "6"
askama = "0.12"

# Queue
dashmap.workspace = true

[features]
default = []
test-utils = []